version: "3.7"
services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "33061:3306"
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
            driver: none
  elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
        container_name: elasticsearch-rails-searchapp
        environment:
            - discovery.type=single-node
            - cluster.name=elasticsearch-rails
            - cluster.routing.allocation.disk.threshold_enabled=false
        volumes:
            - elastic:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        logging:
            driver: none
  web:
    build: ../
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_NAME: ecs_application_db
     DB_PORT: 3306
     DB_HOST: db
     RAILS_ENV: development
     RAILS_MAX_THREADS: 5
     REDIS_HOST: redis
     REDIS_PORT: 6379
     BUNDLE_PATH: /bundle
     ELASTICSEARCH_URL: "http://elasticsearch:9200"
    volumes:
      - ../:/rails-app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
      - "elasticsearch"
  sidekiq:
    build: ../
    command: bundle exec sidekiq
    volumes:
      - ../:/rails-app
    environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_NAME: ecs_application_db
     DB_PORT: 3306
     DB_HOST: db
     RAILS_ENV: development
     REDIS_HOST: redis
     REDIS_PORT: 6379
     ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - "redis"
      - "db"
      - "elasticsearch"
volumes:
  db:
  bundle:
  redis:
  elastic: